a='cardio'
print(len(a))
first=8
second=10
summa=first+second
diff=first-second
print(summa,diff)
first=3
second=5
third=8
mean=(first+second+third)/3
print(mean)
first_string=(str("понедельник"))
second_string=(str("вторник"))
print(first_string+(",")+(second_string))
a=3
b=5
c=7
f=(a*b)+(a*c)
f=(f**3)/2
print(f)
